server:
  servlet:
    context-path: /flamingo

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 60000
        loggerLevel: basic

spring:
  application:
    name: flamingo

auth:
  roles-to-check:
  - PROMOTION_SCHEDULING_READ
  - AFFILIATE_READ
  - BONUS_WRITE

---

spring:
  profiles: default
  cloud:
    consul:
      enabled: true
      host: 10.90.16.11:8500  #malta-stage
      prefix: platform-config
      defaultContext: flamingo
    discovery:
      client:
        simple:
          instances:
            bo-integration:
            - uri: https://stage-malta-internal.leovegas.net:8443/bo-integration
            country:
            - uri: https://stage-malta-internal.leovegas.net:8443/country
            affiliate:
            - uri: https://stage-malta-internal.leovegas.net:8443/affiliate

#spring:
#  profiles: default
#  cloud:
#    consul:
#      enabled: true
#      host: 10.90.18.10:8500 # dev-mr
#      prefix: platform-config
#      defaultContext: flamingo
#    discovery:
#      client:
#        simple:
#          instances:
#            bo-integration:
#            - uri: https://internal-1.leo-dev-mr.lvg-tech.net:8443/bo-integration
#            country:
#            - uri: https://internal-1.leo-dev-mr.lvg-tech.net:8443/country
#            affiliate:
#            - uri: https://internal-1.leo-dev-mr.lvg-tech.net:8443/affiliate
